config = [
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_13_vs_Mic",
        "classes": [13, 13,13, 13,13, 13,13, 13,13, 13]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_14_vs_Mic",
        "classes": [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_18_vs_Mic",
        "classes": [18, 18, 18, 18, 18, 18, 18, 18, 18, 18]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_33_vs_Mic",
        "classes": [33,33,33,33,33,33,33,33,33,33]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_45_vs_Mic",
        "classes": [45,45,45,45,45,45,45,45,45,45]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_48_vs_Mic",
        "classes": [48,48,48,48,48,48,48,48,48,48]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_50_vs_Mic",
        "classes": [50,50,50,50,50,50,50,50,50,50]
    },

    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_0_vs_Mic",
        "classes": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_5_vs_Mic",
        "classes": [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_9_vs_Mic",
        "classes": [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
    },

    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_13_vs_Mic",
        "classes": [13, 13, 13, 13, 13, 13, 13, 13, 13, 13]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_14_vs_Mic",
        "classes": [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_18_vs_Mic",
        "classes": [18, 18, 18, 18, 18, 18, 18, 18, 18, 18]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_33_vs_Mic",
        "classes": [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_45_vs_Mic",
        "classes": [45, 45, 45, 45, 45, 45, 45, 45, 45, 45]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_48_vs_Mic",
        "classes": [48, 48, 48, 48, 48, 48, 48, 48, 48, 48]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "aggregate",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_Linear_50_vs_Mic_",
        "classes": [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
    },
]
config2 = [
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours1",
        "savedir": "../../CAD_Tlinear_0",
        "classes": [0,0,0,0,0]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours1",
        "savedir": "../../CAD_Tlinear_05",
        "classes": [5,5,5,5,5]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours1",
        "savedir": "../../CAD_Tlinear_13",
        "classes": [13,13,13,13,13]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours1",
        "savedir": "../../CAD_Tlinear_14",
        "classes": [14, 14,14,14,14]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours1",
        "savedir": "../../CAD_Tlinear_18",
        "classes": [18, 18,18,18,18]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "1",
        "savedir": "../../CAD_Tlinear_31",
        "classes": [31, 31, 31, 31, 31]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "1ours",
        "savedir": "../../CAD_Tlinear_33",
        "classes": [33, 33, 33, 33, 33]
    },

    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "1ours",
        "savedir": "../../CAD_Tlinear_45",
        "classes": [45, 45, 45, 45, 45]
    },

    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "1ours",
        "savedir": "../../CAD_Tlinear_48",
        "classes": [48, 48, 48, 48, 48]
    },
    {
        "pulse": 6.28,
        "dropout": 0.2,
        "truncation": 8,
        "n_weightpts": 24,  # 48
        "n_feature_weights": 6,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../CAD_Tlinear_50",
        "classes": [50, 50, 50, 50, 50]
    },
]

config_aggregate = [
    {
        "pulse": 6.28,
        "dropout": 0.5,
        "truncation": 8,
        "n_weightpts": 16,  # 48
        "n_feature_weights": 16,  # 6
        "pl": 16,  # 16,
        "neighbours": 32,
        "R": .1,
        "c": 1000,
        "nu": .6,
        "center_fixed": True,
        "output_dimension": 200,# 128,
        "biases": False,
        "spatial": "RBFN-norelu",
        "semantic": "linear",
        "TL_path": None,  # "./save/AD_TL/state_dict.pth",
        "notes": " con CompositeLayer",
        "rootdir": "../../data/shapenetcorev2_hdf5_2048",
        "architecture": "ours",
        "savedir": "../../AD_linear_fixed_48",
        "classes": [48, 48, 48, 48, 48]
    }
]


classification_cfgs = [
{
    "pulse": 6.28,
    "dropout": 0.5,
    "truncation": 8,
    "n_weightpts": 32,
    "n_feature_weights" : 16,
    "pl": 64,
    "neighbours": 32,
    "spatial" : "RBFN-norelu",
    "semantic" : "aggregate",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir": "../../data/multiclass",
    "epochs": 100,
    "architecture": "FourierModelNet40",
    "schedule": [20, 40, 60]# shapenetcorev2_hdf5_2048 [3, 5, 8, 13],

},

    ####
    ####
    #### MLP
{
    "pulse": 6.28,
    "dropout": 0.3,
    "truncation": 8,
    "n_weightpts": 16,
    "n_feature_weights" : 16,
    "pl": 64,
    "neighbours": 32,
    "spatial" : "MLP",
    "semantic" : "linear",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir" : "../../data/multiclass",
    "epochs" : 70,
    "architecture" : "FourierModelNet40",
    "schedule" : [20, 35, 50, 70],
},
{
    "pulse": 6.28,
    "dropout": 0.3,
    "truncation": 8,
    "n_weightpts": 16,
    "n_feature_weights" : 16,
    "pl": 32,
    "neighbours": 32,
    "spatial" : "MLP",
    "semantic" : "linear",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir": "../../data/shapenetcorev2_hdf5_2048",
    "epochs": 20,
    "architecture": "FourierModelNet40",
    "schedule": [3, 5, 8, 13],

},
    ####
    ####
    #### Trained RBFN
{
    "pulse": 6.28,
    "dropout": 0.4,
    "truncation": 8,
    "n_weightpts": 16,
    "n_feature_weights" : 16,
    "pl": 64,
    "neighbours": 32,
    "spatial": "CompositeLayer",
    "semantic" : "aggregate",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir" : "./data/multiclass",
    "epochs" : 500,
    "architecture" : "CompositeNet",
    "schedule" : [30,60,90] #[20, 35, 50, 70],
},
    ####
    ####
    #### AGGREGATE
{
    "pulse": 6.28,
    "dropout": 0.2,
    "truncation": 8,
    "n_weightpts": 16,
    "n_feature_weights" : 16,
    "pl": 64,
    "neighbours": 32,
    "spatial" : "TRBFN-norelu",
    "semantic" : "aggregate",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir" : "../../data/multiclass",
    "epochs" : 70,
    "architecture" : "FourierModelNet40",
    "schedule" : [20, 35, 50, 70],
},
{
    "pulse": 6.28,
    "dropout": 0.2,
    "truncation": 8,
    "n_weightpts": 16,
    "n_feature_weights" : 16,
    "pl": 32,
    "neighbours": 32,
    "spatial" : "TRBFN-norelu",
    "semantic" : "aggregate",
    "biases" : True,
    "notes" : " 16 fw ",
    "rootdir": "../../data/shapenetcorev2_hdf5_2048",
    "epochs": 20,
    "architecture": "FourierModelNet40",
    "schedule": [3, 5, 8, 13],

},]